name: Code Quality Checks

on: 
    pull_request:
        branches: [ main, dev ]
    push: 
        branches: [ main, dev ]


jobs: 
    pylint-code-quality:
        name: PyLint Code Quality
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.12"]
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v3
          with:
              python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install pylint
        - name: Analysing the code with pylint
          run: |
              echo 'TEST_RESULTS<<EOF' >> $GITHUB_OUTPUT
              echo "$(pylint $(git ls-files '*.py') || true)\n" >> $GITHUB_OUTPUT 
              echo 'EOF' >> $GITHUB_OUTPUT
          id: run_pylint
        - name: post test results
          uses: mshick/add-pr-comment@v2
          with:
            message: |
                🧐 PYLINT RESULTS
                ${{ join(steps.run_pylint.outputs.*, '\n') }}