# This is a basic workflow to help you get started with Actions

name: Test and Integrate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-unittests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install MicroPython
        uses: BrianPugh/install-micropython@v2

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: install micropython unittests
        run: micropython -m mip install unittest

      - name: run unittests
        run: |
            echo 'TEST_RESULTS<<EOF' >> $GITHUB_OUTPUT
            echo '$(micropython tests.py)\n' >> $GITHUB_OUTPUT 
            echo 'EOF' >> $GITHUB_OUTPUT
        id: test_results

      - name: post test results
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            {
              🧪 TEST RESULTS
              ${{steps.test_results.outputs.*}}
            }